# Generated by Django 4.2.5 on 2023-09-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myusers',
            table='myusers',
        ),
    ]
